<!DOCTYPE html>
<html lang="en" >

<head>
    
    <meta charset="UTF-8">
    
    <title>Repawsitory | Pet Records</title>
    
    <!-- For Responsivness --> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta name="author" content="Logistic Solutions"> 
    <meta name="description" content="Repawsitory | Online Pet Records.">

    <!-- Favicon | generated by realfavicongenerator.net --> 
    <link rel="apple-touch-icon" sizes="180x180" href="../img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/favicon/favicon-16x16.png">
    <link rel="manifest" href="../img/favicon/site.webmanifest">
    <link rel="mask-icon" href="../img/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#00aba9">
    <meta name="theme-color" content="#ffffff">

    <!-- Open Graph | SEO Optimization -->
    <meta property="og:title" content="Repawsitory | Pet Records" />
    <meta property="og:description" content="Online pet record storage." />
    <meta property="og:url" content="http://repaw.io/" />
    <meta property="og:image" content="../img/logo/repaw_logo.jpg" />
    
    <meta name="robots" content="index, follow">
